
services:
  web:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html

    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inmobiliaria
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: